name: Docker Workflow

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21' 
          cache: 'maven'
          
      - name: Run Dependency Check
        run: mvn dependency-check:check

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v5
              with:
                gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Enable Docker Content Trust
        run: export DOCKER_CONTENT_TRUST=1
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/java_app:1.0.${{ github.run_number }}
          build-args:
            "VERSION=1.0.${{github.run_number}}"
          sign: true 
          signing_key: ${{ steps.import_gpg.outputs.fingerprint }}
          
      - name: Install Snyk
        uses: snyk/actions/setup@master
      
      - name: Scan Docker Image wih Snyk
        run: snyk container test ${{ secrets.DOCKER_USERNAME }}/java_app:1.0.${{ github.run_number }}
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        continue-on-error: true
# comment2

        
